"""Initial tables

Revision ID: aa4924ce1349
Revises: 
Create Date: 2025-12-15 15:50:03.591437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4924ce1349'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mz_mfp_org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jgmc', sa.String(length=80), nullable=False, comment='医疗机构名称'),
    sa.Column('zzjgdm', sa.String(length=22), nullable=False, comment='组织机构代码'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zzjgdm')
    )
    op.create_index(op.f('ix_mz_mfp_org_id'), 'mz_mfp_org', ['id'], unique=False)
    op.create_table('mz_mfp_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('patient_no', sa.String(length=50), nullable=False, comment='病历号/就诊标识'),
    sa.Column('visit_time', sa.DateTime(), nullable=False, comment='就诊时间JZSJ'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft/submitted'),
    sa.Column('dept_code', sa.String(length=50), nullable=False, comment='科室代码'),
    sa.Column('doc_code', sa.String(length=50), nullable=False, comment='医生代码'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号'),
    sa.Column('prefill_snapshot', sa.JSON(), nullable=True, comment='外部视图原始快照'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['mz_mfp_org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_record_id'), 'mz_mfp_record', ['id'], unique=False)
    op.create_table('mz_mfp_base_info',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='系统登录用户名'),
    sa.Column('jzkh', sa.String(length=50), nullable=False, comment='就诊卡号'),
    sa.Column('xm', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('xb', sa.String(length=1), nullable=False, comment='性别RC001'),
    sa.Column('csrq', sa.Date(), nullable=False, comment='出生日期'),
    sa.Column('hy', sa.String(length=1), nullable=False, comment='婚姻RC002'),
    sa.Column('gj', sa.String(length=40), nullable=False, comment='国籍'),
    sa.Column('mz', sa.String(length=2), nullable=False, comment='民族RC035'),
    sa.Column('zjlb', sa.String(length=1), nullable=False, comment='证件类别RC038'),
    sa.Column('zjhm', sa.String(length=18), nullable=False, comment='证件号码'),
    sa.Column('xzz', sa.String(length=200), nullable=False, comment='现住址'),
    sa.Column('lxdh', sa.String(length=40), nullable=False, comment='联系电话'),
    sa.Column('ywgms', sa.String(length=1), nullable=False, comment='药物过敏史RC037'),
    sa.Column('gmyw', sa.String(length=500), nullable=True, comment='过敏药物'),
    sa.Column('qtgms', sa.String(length=1), nullable=True, comment='其他过敏史RC037'),
    sa.Column('qtgmy', sa.String(length=200), nullable=True, comment='其他过敏原'),
    sa.Column('ghsj', sa.DateTime(), nullable=True, comment='挂号时间'),
    sa.Column('bdsj', sa.DateTime(), nullable=True, comment='报到时间'),
    sa.Column('jzsj', sa.DateTime(), nullable=False, comment='就诊时间'),
    sa.Column('jzks', sa.String(length=100), nullable=True, comment='就诊科室'),
    sa.Column('jzksdm', sa.String(length=50), nullable=False, comment='就诊科室代码'),
    sa.Column('jzys', sa.String(length=40), nullable=False, comment='接诊医师'),
    sa.Column('jzyszc', sa.String(length=40), nullable=False, comment='接诊医师职称'),
    sa.Column('jzlx', sa.String(length=1), nullable=False, comment='就诊类型RC041'),
    sa.Column('fz', sa.String(length=1), nullable=False, comment='是否复诊RC016'),
    sa.Column('sy', sa.String(length=1), nullable=False, comment='是否输液RC016'),
    sa.Column('mzmtbhz', sa.String(length=1), nullable=False, comment='是否慢特病RC016'),
    sa.Column('jzhzfj', sa.String(length=1), nullable=True, comment='急诊患者分级RC042'),
    sa.Column('jzhzqx', sa.String(length=1), nullable=True, comment='急诊患者去向RC045'),
    sa.Column('zyzkjsj', sa.DateTime(), nullable=True, comment='住院证开具时间'),
    sa.Column('hzzs', sa.String(length=1500), nullable=True, comment='患者主诉'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('mz_mfp_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('diag_type', sa.String(length=30), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False, comment='序号'),
    sa.Column('diag_name', sa.String(length=100), nullable=False, comment='诊断名称'),
    sa.Column('diag_code', sa.String(length=50), nullable=True, comment='诊断编码'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_diagnosis_diag_type'), 'mz_mfp_diagnosis', ['diag_type'], unique=False)
    op.create_index(op.f('ix_mz_mfp_diagnosis_id'), 'mz_mfp_diagnosis', ['id'], unique=False)
    op.create_table('mz_mfp_export_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=20), nullable=False, comment='xlsx/print'),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_export_log_id'), 'mz_mfp_export_log', ['id'], unique=False)
    op.create_table('mz_mfp_fee_summary',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('zfy', sa.Numeric(precision=11, scale=2), nullable=False, comment='总费用'),
    sa.Column('zfje', sa.Numeric(precision=10, scale=2), nullable=False, comment='自付金额'),
    sa.Column('ylfwf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zlczf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hlf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qtfy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('blzdf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zdf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yxxzdf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lczdxmf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fsszlxmf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zlf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sszlf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mzf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ssf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kff', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zyl_zyzd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zyzl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zywz', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zygs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zcyjf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zytnzl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zygczl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zytszl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zyqt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zytstpjg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bzss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('xyf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kjywf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zcyf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zyzjf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zcyf1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pfklf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('xf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bdbblzpf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qdbblzpf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nxyzlzpf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('xbyzlzpf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('jcyyclf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yyclf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ssycxclf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qtf', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('mz_mfp_field_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False, comment='字段名'),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_source', sa.String(length=20), nullable=False, comment='manual/dict/prefill'),
    sa.Column('operator_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_field_audit_id'), 'mz_mfp_field_audit', ['id'], unique=False)
    op.create_table('mz_mfp_herb_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False, comment='序号'),
    sa.Column('herb_type', sa.String(length=1), nullable=False, comment='中草药类别'),
    sa.Column('route_code', sa.String(length=30), nullable=False, comment='用药途径代码'),
    sa.Column('route_name', sa.String(length=100), nullable=False, comment='用药途径名称'),
    sa.Column('dose_count', sa.Integer(), nullable=False, comment='剂数'),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_herb_detail_id'), 'mz_mfp_herb_detail', ['id'], unique=False)
    op.create_table('mz_mfp_medication_summary',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('xysy', sa.String(length=1), nullable=False, comment='是否使用西药RC016'),
    sa.Column('zcysy', sa.String(length=1), nullable=False, comment='是否使用中成药RC016'),
    sa.Column('zyzjsy', sa.String(length=1), nullable=False, comment='是否使用中药制剂RC016'),
    sa.Column('ctypsy', sa.String(length=1), nullable=False, comment='是否使用传统饮片RC016'),
    sa.Column('pfklsy', sa.String(length=1), nullable=False, comment='是否使用配方颗粒RC016'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('mz_mfp_surgery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False, comment='序号'),
    sa.Column('op_name', sa.String(length=100), nullable=False, comment='手术名称'),
    sa.Column('op_code', sa.String(length=20), nullable=False, comment='手术编码'),
    sa.Column('op_time', sa.DateTime(), nullable=False, comment='手术日期'),
    sa.Column('operator_name', sa.String(length=40), nullable=False, comment='操作者'),
    sa.Column('anesthesia_method', sa.String(length=6), nullable=False, comment='麻醉方式RC013'),
    sa.Column('anesthesia_doctor', sa.String(length=40), nullable=False, comment='麻醉医师'),
    sa.Column('surgery_level', sa.Integer(), nullable=False, comment='手术分级RC029'),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_surgery_id'), 'mz_mfp_surgery', ['id'], unique=False)
    op.create_table('mz_mfp_tcm_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False, comment='序号'),
    sa.Column('op_name', sa.String(length=100), nullable=False, comment='操作名称'),
    sa.Column('op_code', sa.String(length=20), nullable=False, comment='操作编码'),
    sa.Column('op_times', sa.Integer(), nullable=False, comment='操作次数'),
    sa.Column('op_days', sa.Integer(), nullable=True, comment='操作天数'),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['mz_mfp_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mz_mfp_tcm_operation_id'), 'mz_mfp_tcm_operation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mz_mfp_tcm_operation_id'), table_name='mz_mfp_tcm_operation')
    op.drop_table('mz_mfp_tcm_operation')
    op.drop_index(op.f('ix_mz_mfp_surgery_id'), table_name='mz_mfp_surgery')
    op.drop_table('mz_mfp_surgery')
    op.drop_table('mz_mfp_medication_summary')
    op.drop_index(op.f('ix_mz_mfp_herb_detail_id'), table_name='mz_mfp_herb_detail')
    op.drop_table('mz_mfp_herb_detail')
    op.drop_index(op.f('ix_mz_mfp_field_audit_id'), table_name='mz_mfp_field_audit')
    op.drop_table('mz_mfp_field_audit')
    op.drop_table('mz_mfp_fee_summary')
    op.drop_index(op.f('ix_mz_mfp_export_log_id'), table_name='mz_mfp_export_log')
    op.drop_table('mz_mfp_export_log')
    op.drop_index(op.f('ix_mz_mfp_diagnosis_id'), table_name='mz_mfp_diagnosis')
    op.drop_index(op.f('ix_mz_mfp_diagnosis_diag_type'), table_name='mz_mfp_diagnosis')
    op.drop_table('mz_mfp_diagnosis')
    op.drop_table('mz_mfp_base_info')
    op.drop_index(op.f('ix_mz_mfp_record_id'), table_name='mz_mfp_record')
    op.drop_table('mz_mfp_record')
    op.drop_index(op.f('ix_mz_mfp_org_id'), table_name='mz_mfp_org')
    op.drop_table('mz_mfp_org')
    # ### end Alembic commands ###
